on:
  push: []
  pull_request: []
name: test

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    env:
      DENO_DIR: ${{ github.workspace }}/.deno
    steps:
    - uses: actions/checkout@main
      if: github.event_name != 'pull_request'
    - uses: actions/checkout@main
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.pull_request.head.sha }}
    - uses: denoland/setup-deno@main
      with:
        deno-version: v1.x
    - uses: actions/cache@v2
      with:
        path: ${{ env.DENO_DIR }}
        key: ${{ runner.os }}-test
    - run: 'deno cache --unstable *_test.ts **/*_test.ts'
    - run: 'deno test --unstable --allow-read=.'
